### ISSUE TITLE
[홈탭] 안드로이드 아이콘 노출 개선

### ISSUE THREAD

**Issue by Pluu** [droidknights/DroidKnights2021_App#1]
## Kind (Required)

- Improvement

## Overview (Required)

안드로이드 아이콘에는 8dp의 Radius로 노출되어야합니다.

### Current

![device-2021-07-21-232205](https://user-images.githubusercontent.com/1534926/126504913-745e8e66-781f-4327-b57b-3a56ed5f1875.png)

### Design 

![Screenshot 2021-07-21 at 23-03-19 Zeplin - Projects](https://user-images.githubusercontent.com/1534926/126502279-b8f735aa-a24a-44c4-97e0-de9dad70ab3b.png)

## Links

- https://github.com/droidknights/DroidKnights2021_App/blob/main/features/home/src/main/res/layout/item_info_header.xml#L46

**Comment by l2hyunwoo** [comment]
해보겠습니다! 🙋‍♂️

**Comment by Pluu** [comment]
@l2hyunwoo thx
