### ISSUE TITLE
[홈탭] 스폰서 자동 스크롤

### ISSUE THREAD

**Issue by Pluu** [droidknights/DroidKnights2021_App#2]
## Kind (Required)

- Improvement

## Overview (Required)

- 스폰서 영역이 자동 스크롤이 지원되어야 합니다.
- 자동 스크롤 방향은 `오른쪽에서 왼쪽으로` 흐르기가 되어야합니다 
- (Option) 해당 영역을 Compose로 개선 
  - (Required) 외부에서 사용하는 RecyclerView.Adapter 및 ViewHolder 패턴을 유지해야합니다

![device-2021-07-21-232205](https://user-images.githubusercontent.com/1534926/126506200-b39c5833-070b-454c-b8bd-42d1901d7043.png) 

## Link
- https://developer.android.com/jetpack/compose/interop/compose-in-existing-ui
- https://proandroiddev.com/infinite-auto-scrolling-lists-with-recyclerview-lazylists-in-compose-1c3b44448c8

**Comment by l2hyunwoo** [comment]
🙋‍♂️ 이 부분 compose로 개선하는 작업까지 해보고 싶습니다

**Comment by Pluu** [comment]
@l2hyunwoo thx

**Comment by Pluu** [comment]
Compose 사용시 필수 요구 조건을 갱신했습니다
cc @l2hyunwoo
