### ISSUE TITLE
사용하지 않는 Qualifier 제거

### ISSUE THREAD

**Issue by Pluu** [droidknights/DroidKnights2021_App#20]
## Kind (Required)

- Other

## Overview (Required)

- 정의되었지만, 사용하지않는 Qualifier는 삭제해야하는 대상입니다.

## Links

- https://github.com/droidknights/DroidKnights2021_App/blob/main/shared/src/main/java/com/droidknights/app2021/shared/di/CoroutinesQualifiers.kt#L23

**Comment by jsh-me** [comment]
🙋‍♂️ 제가 해봐도 괜찮을까요~?!

**Comment by Pluu** [comment]
@jsh-me thx
