### ISSUE TITLE
Gradle Kotlin DSL

### ISSUE THREAD

**Issue by zmunm** [droidknights/DroidKnights2021_App#24]
## Kind (Required)

- Other

## Overview (Required)

- settings.gradle.kts 파일만 DSL로 작성되어 있어서, 다른 gradle 파일들도 DSL로 마이그레이션하면 어떨까 합니다.

## Links

- https://github.com/droidknights/DroidKnights2021_App/blob/main/settings.gradle.kts

**Comment by Pluu** [comment]
@zmunm PR 올려주시면 감사합니다 :)

참고로, Android Studio Arctic Fox 알파+베타에서는 kts에서 스크립트 로딩+캐싱 이슈로 에러 노출처럼 되어서, 모듈 부분은 gradle 을 사용했습니다.

현재 버전에서 문제가 없다면 kts로도 이관해도 무방합니다.
