### ISSUE TITLE
[홈탭] 올해 행사 일자 문구 노출 수정 

### ISSUE THREAD

**Issue by Pluu** [droidknights/DroidKnights2021_App#3]
## Kind (Required)

- Improvement

## Overview (Required)

- 2021년 행사는 `2021년 9월 25일`이므로 문구 수정이 필요합니다

### Current

![device-2021-07-21-234655](https://user-images.githubusercontent.com/1534926/126509012-ad8808f4-a1c0-4278-bc55-4615a5f78ab6.png) 

## Links

- https://github.com/droidknights/DroidKnights2021_App/blob/main/features/home/src/main/java/com/droidknights/app2021/home/databinding/adapters/ViewBindingadapter.kt#L27

**Comment by l2hyunwoo** [comment]
해보겠습니다! 🙋‍♂️

**Comment by Pluu** [comment]
@l2hyunwoo thx
