### ISSUE TITLE
[홈탭] 스폰서/이벤트 클릭시 앱내에서 웹뷰를 노출

### ISSUE THREAD

**Issue by Pluu** [droidknights/DroidKnights2021_App#4]
## Kind (Required)

- Improvement

## Overview (Required)

- 스폰서와 이벤트 클릭시 androidx.browser:browser의 Chrome custom tab을 활용해서 앱내에서 웹뷰가 노출되도록 한다
- 현재는 디바이스에 설치된 웹 브라우저 앱을 통해서 웹페이지 노출

## Links

- https://github.com/droidknights/DroidKnights2021_App/blob/main/features/home/src/main/java/com/droidknights/app2021/home/ui/HomeFragment.kt#L43
- https://github.com/droidknights/DroidKnights2021_App/blob/main/features/home/src/main/java/com/droidknights/app2021/home/ui/HomeFragment.kt#L49

**Comment by kts6056** [comment]
💇‍♂️ 제가 해봐도 될까요?

**Comment by Pluu** [comment]
@kts6056 thx
