### ISSUE TITLE
[홈탭] 이벤트간의 Divider 노출

### ISSUE THREAD

**Issue by Pluu** [droidknights/DroidKnights2021_App#5]
## Kind (Required)

- Improvement

## Overview (Required)

- 각 이벤트간의 사이에는 Divider가 추가되어야합니다
- Divider는 1dp 높이의 #F1F1F1 색상

### Current

![device-2021-07-21-234655](https://user-images.githubusercontent.com/1534926/126513005-8d339ead-ba0a-422d-8d1e-35dfeefaf8f3.png)

### Design

<img width="816" alt="스크린샷 2021-07-22 오전 12 12 46" src="https://user-images.githubusercontent.com/1534926/126513964-197df090-cbc3-4a62-8658-0f15c7d5d1c5.png">

**Comment by fornewid** [comment]
🙋‍♂️

**Comment by Pluu** [comment]
@fornewid thx
