### ISSUE TITLE
[스케쥴] 트랙 노출 순서 개선

### ISSUE THREAD

**Issue by Pluu** [droidknights/DroidKnights2021_App#6]
## Kind (Required)

- Improvement

## Overview (Required)

- 트랙 순서는 `Track1 > Track2 > Etc` 순서로 노출되어야합니다.
- 현재는 트랙이 노출되는 순서는 json에 track이 저장된 순서에 영향을 받습니다.

### Info

- 세션의 트랙 정보 : https://github.com/droidknights/DroidKnights2021_App/blob/main/app/src/main/assets/sessions.json#L80
- (Required) json의 순서를 수정해서는 안됩니다.

### Current

<img src="https://user-images.githubusercontent.com/1534926/126517494-65050849-7ff5-4a38-a4f0-9586a2f5d49f.png" width="50%" />

## Links

- https://github.com/droidknights/DroidKnights2021_App/blob/main/features/schedule/src/main/java/com/droidknights/app2021/schedule/ScheduleScreen.kt#L32

**Comment by BeokBeok** [comment]
🙋‍♂️ 제가 해봐도 될까요?

**Comment by Pluu** [comment]
@BeokBeok thx
