### ISSUE TITLE
[스케쥴] 세션 노출 순서 개선

### ISSUE THREAD

**Issue by Pluu** [droidknights/DroidKnights2021_App#7]
## Kind (Required)

- Improvement

## Overview (Required)

- 세션 노출은 `시간-세션명` 순서대로 노출되어야합니다

### Current

- 현재 세션 리스트는 json에 저장된 순서대로 노출됩니다.

| 참고 자료 | 참고 자료 |
| :---: | :---: |
| ![device-2021-08-07-131845](https://user-images.githubusercontent.com/1534926/128587700-7f070d99-5887-4c6a-a25a-1640db5573f8.png)  | ![device-2021-07-26-234914](https://user-images.githubusercontent.com/1534926/127009757-3903589f-e700-48fd-89a8-a6eb1646c071.png) |

## Links

- https://github.com/droidknights/DroidKnights2021_App/blob/main/domain/src/main/java/com/droidknights/app2021/domain/usecase/session/GetSessionsUseCase.kt#L28
- https://github.com/droidknights/DroidKnights2021_App/blob/main/app/src/main/assets/sessions.json#L12

**Comment by l2hyunwoo** [comment]
🙋‍♂️

**Comment by Pluu** [comment]
Updated Image

**Comment by Pluu** [comment]
@l2hyunwoo 다양한 사람에게 컨트리뷰트 기회를 주고자, 동시에 가능한 이슈(Open된)는 한시적으로 제한된 상태입니다.

선행 작업을 먼저 부탁드립니다.

**Comment by l2hyunwoo** [comment]
@Pluu 네 알겠습니다!

**Comment by WonJoongLee** [comment]
제가 해보고 싶습니다!🙋‍♂️

**Comment by Pluu** [comment]
@WonJoongLee thx
