### ISSUE TITLE
[KSerializer] json을 DTO로 만들때의 직렬화 개선

### ISSUE THREAD

**Issue by Pluu** [droidknights/DroidKnights2021_App#8]
## Kind (Required)

- Improvement
 
## Overview (Required)

- json에 있는 트랙정보는 String으로 정의되어 있어 DTO 변환시 값에 영향을 받습니다. 유연한 대응을 위해서 직렬화 개선이 필요합니다.
- (Required) Track1, track1은 Room.Track1으로 매칭됩니다.
- (Required) 트랙정보가 올바르게 매칭되지 않을시 Room.Etc로 매칭됩니다.

## Links

- KSerializer 사용
   - https://github.com/Kotlin/kotlinx.serialization/blob/master/guide/example/example-builtin-03.kt#L11
   - https://github.com/Kotlin/kotlinx.serialization/blob/master/core/commonMain/src/kotlinx/serialization/builtins/LongAsStringSerializer.kt
- DTO 정보 : https://github.com/droidknights/DroidKnights2021_App/blob/main/data/src/main/java/com/droidknights/app2021/data/model/SessionData.kt#L22
- Room 정보 : https://github.com/droidknights/DroidKnights2021_App/blob/main/shared/src/main/java/com/droidknights/app2021/shared/Domain.kt#L20

**Comment by neulbo27** [comment]
🙋‍♂️ 제가 개선 해봐도 될까요?

참고에 적어주신 내용 참고해서 개선할 때 커스텀 Serializer 클래스를 새로 생성하게 될 것 같은데 해당 클래스를 data 모듈 안에 seralization 패키지를 생성해서 넣어도 괜찮을까요?
혹은 컨벤션에 적합한 경로를 알려주시면 해당 경로에 생성해 작업해보겠습니다.

**Comment by Pluu** [comment]
@neulbo27 thx

해당 클래스가 존재하는 동일한 모듈내에 생성해주시면 됩니다. 언급하신대로 seralization로 부탁드립니다.
